"""edited user models

Revision ID: 04612d4a661c
Revises: 1bac0d077374
Create Date: 2023-10-03 16:23:05.633168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04612d4a661c'
down_revision = '1bac0d077374'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
